version: '3.8'
services:
  db:
    image: mysql-bugless
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin   
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: bugless
    ports:
      - "3306:3306"
    networks:
      - devs2blu-network 
  backend-bugless:
    image: backend-bugless
    restart: always
    build: ./Back-End-BugLess
    working_dir: /Back-End-BugLess
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./Back-End-BugLess:/Back-End-BugLess
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - devs2blu-network
      


networks:
    devs2blu-network:
        driver: bridge